const express = require('express');
const multer = require('multer');
const router = express.Router();
const { requireAuth, requireRole } = require('../middleware/authMiddleware');
const importController = require('../controllers/importController');
const dkclHueF13SyncController = require('../controllers/dkclHueF13SyncController');
const dkclSharedOperationsController = require('../controllers/dkclSharedOperationsController');
const autoBackfillCoverageController = require('../controllers/autoBackfillCoverageController');
const autoBackfillQueueController = require('../controllers/autoBackfillQueueController');

const upload = multer({ storage: multer.memoryStorage() });
const adminOnly = [requireAuth, requireRole(['admin'])];

router.post('/upload', ...adminOnly, upload.single('file'), importController.upload.bind(importController));
router.get('/f13/status', ...adminOnly, importController.status.bind(importController));
router.get('/status', ...adminOnly, importController.status.bind(importController));
router.get('/auto-backfill/coverage', requireAuth, autoBackfillCoverageController.getCoverage.bind(autoBackfillCoverageController));
router.post('/auto-backfill/runs', ...adminOnly, autoBackfillQueueController.createRun.bind(autoBackfillQueueController));
router.get('/auto-backfill/runs/:runId', requireAuth, autoBackfillQueueController.getRun.bind(autoBackfillQueueController));
router.post('/auto-backfill/runs/:runId/pause', ...adminOnly, autoBackfillQueueController.pauseRun.bind(autoBackfillQueueController));
router.post('/auto-backfill/runs/:runId/resume', ...adminOnly, autoBackfillQueueController.resumeRun.bind(autoBackfillQueueController));
router.post('/dkcl/session/preflight', ...adminOnly, dkclSharedOperationsController.preflight.bind(dkclSharedOperationsController));
router.post('/dkcl/session/interactive-auth', ...adminOnly, dkclSharedOperationsController.interactiveAuthenticate.bind(dkclSharedOperationsController));
router.post('/dkcl/session/cancel-login', ...adminOnly, dkclSharedOperationsController.cancelLogin.bind(dkclSharedOperationsController));
router.post('/dkcl/session/recover', ...adminOnly, dkclSharedOperationsController.recover.bind(dkclSharedOperationsController));
router.get('/dkcl/hue/f13/coverage-summary', ...adminOnly, dkclHueF13SyncController.getCoverageSummary.bind(dkclHueF13SyncController));
router.get('/dkcl/hue/f13/missing-dates', ...adminOnly, dkclHueF13SyncController.scanMissingDates.bind(dkclHueF13SyncController));
router.get('/dkcl/tct/f13/coverage-summary', ...adminOnly, dkclSharedOperationsController.getTctCoverageSummary.bind(dkclSharedOperationsController));
router.get('/dkcl/tct/f13/missing-dates', ...adminOnly, dkclSharedOperationsController.scanTctMissingDates.bind(dkclSharedOperationsController));
router.post('/dkcl/tct/f13/backfill-queue', ...adminOnly, dkclSharedOperationsController.startTctBackfillQueue.bind(dkclSharedOperationsController));
router.get('/dkcl/tct/f13/backfill-queue/active', ...adminOnly, dkclSharedOperationsController.getTctBackfillQueue.bind(dkclSharedOperationsController));
router.get('/dkcl/tct/f13/backfill-queue/:queueId', ...adminOnly, dkclSharedOperationsController.getTctBackfillQueue.bind(dkclSharedOperationsController));
router.post('/dkcl/tct/f13/backfill-queue/:queueId/stop', ...adminOnly, dkclSharedOperationsController.stopTctBackfillQueue.bind(dkclSharedOperationsController));
router.post('/dkcl/tct/f13/backfill-queue/:queueId/retry', ...adminOnly, dkclSharedOperationsController.retryTctBackfillQueueItem.bind(dkclSharedOperationsController));
router.post('/dkcl/hue/f13/backfill-queue', ...adminOnly, dkclHueF13SyncController.startBackfillQueue.bind(dkclHueF13SyncController));
router.get('/dkcl/hue/f13/backfill-queue/active', ...adminOnly, dkclHueF13SyncController.getBackfillQueue.bind(dkclHueF13SyncController));
router.get('/dkcl/hue/f13/backfill-queue/:queueId', ...adminOnly, dkclHueF13SyncController.getBackfillQueue.bind(dkclHueF13SyncController));
router.post('/dkcl/hue/f13/backfill-queue/:queueId/stop', ...adminOnly, dkclHueF13SyncController.stopBackfillQueue.bind(dkclHueF13SyncController));
router.post('/dkcl/hue/f13/backfill-queue/:queueId/retry', ...adminOnly, dkclHueF13SyncController.retryBackfillQueueItem.bind(dkclHueF13SyncController));
router.post('/dkcl/hue/f13/sync', ...adminOnly, dkclHueF13SyncController.start.bind(dkclHueF13SyncController));
router.get('/dkcl/hue/f13/sync/:runId', ...adminOnly, dkclHueF13SyncController.getStatus.bind(dkclHueF13SyncController));

module.exports = router;
